//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSMControl.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------------------------------------------------------------------------------------SCHEMA CREATION----------------------------------------------------------------------------------------------------------------------
        ///IF NOT EXISTS
        ///(
        ///  SELECT s.name
        ///   FROM sys.schemas s
        ///   WHERE s.name = &apos;MSM&apos;
        ///)
        ///  BEGIN
        ///    DECLARE @MSM NVARCHAR(MAX);
        ///    SET @MSM = &apos;CREATE SCHEMA MSM AUTHORIZATION dbo;&apos;;
        ///    --PRINT @SQL
        ///    EXEC sys.sp_executesql @MSM;
        ///  END;
        ///--------------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MSM_TABLE_CREATE {
            get {
                return ResourceManager.GetString("MSM_TABLE_CREATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to --IF OBJECT_ID (&apos;MSM.FiscalYear&apos;) IS NULL BEGIN CREATE TABLE MSM.FiscalYear(YearID INT NOT NULL,YearDesc VARCHAR(10) NOT NULL,PRIMARY KEY (YearID)) END;
        ///
        ///--IF OBJECT_ID (&apos;MSM.Configuration&apos;) IS NULL BEGIN CREATE TABLE MSM.Configuration(CID INT NOT NULL,YearID INT NOT NULL,Current_Year VARCHAR(10),IsAdmin BIT,ColorID INT,Background VARCHAR(MAX),PRIMARY KEY (CID),FOREIGN KEY ([YearID]) REFERENCES [MSM].[FiscalYear] ([YearID]))END;
        ///
        ///
        ///
        ///
        ///--IF OBJECT_ID (&apos;MSM.CompanyMasterInfo&apos;) IS NULL BEGIN CREATE TABLE  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MSM_UPDATE_TABLE_ON_MAIN {
            get {
                return ResourceManager.GetString("MSM_UPDATE_TABLE_ON_MAIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///IF OBJECT_ID (&apos;MSM.StoreGodown&apos;) IS NULL BEGIN CREATE TABLE [MSM].[StoreGodown]( [GodID] INT NOT NULL,[GodName] NVARCHAR(80) NULL,[GodCode] NVARCHAR(50) NULL,[GodAddress]  NVARCHAR(50) NULL,[ActiveStatus] BIT NULL,[UserID] INT NULL,[DateCreated] DATETIME NULL,[MUserID] INT	NULL,[ModifiedDate] DATETIME NULL PRIMARY KEY (GodID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid) ,FOREIGN KEY (MUserID) REFERENCES [MSM].[UsersMaster] (userid)) END;
        ///
        ///IF OBJECT_ID (&apos;MSM.ProductCategory&apos;) IS NULL BEGIN  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MSM_UPDATE_TABLE_ON_MASTER {
            get {
                return ResourceManager.GetString("MSM_UPDATE_TABLE_ON_MASTER", resourceCulture);
            }
        }
    }
}
