----------------------------------------------------------------------------------------------------------------------SCHEMA CREATION----------------------------------------------------------------------------------------------------------------------
IF NOT EXISTS
(
  SELECT s.name
   FROM sys.schemas s
   WHERE s.name = 'MSM'
)
  BEGIN
    DECLARE @MSM NVARCHAR(MAX);
    SET @MSM = 'CREATE SCHEMA MSM AUTHORIZATION dbo;';
    --PRINT @SQL
    EXEC sys.sp_executesql @MSM;
  END;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------ROLE TABLES AND INSERT QUERY--------------------------------------------------------------------------------------------------------
IF OBJECT_ID ('[MSM].[UsersRole]') IS NULL BEGIN CREATE TABLE [MSM].[UsersRole]([RoleId] INT NOT NULL,[RoleName] [varchar] (20) NOT NULL,[RoleStatus][bit] null,[Creator][int] NULL CONSTRAINT [PK_UserRole] PRIMARY KEY (RoleId))END;
INSERT INTO [MSM].[UsersRole] ([RoleId],[RoleName],[RoleStatus],[Creator]) VALUES (1,'admin',1,1);
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------USER TABLES AND INSERT QUERY--------------------------------------------------------------------------------------------------------
IF OBJECT_ID ('[MSM].[UsersMaster]') IS NULL BEGIN CREATE TABLE [MSM].[UsersMaster]([userid] [int] NOT NULL,[usrname] [varchar](20) NOT NULL,[loginid] [varchar](20) NOT NULL,[password] [varchar](15) NOT NULL,[dept] [varchar](10) NULL,[RoleID] int NOT NULL,[ActiveStatus] [BIT],[IsAdmin] [bit] NULL,[ColorID] [int] NULL,Background VARCHAR(MAX) NULL CONSTRAINT [PK_MasterUsersMaster] PRIMARY KEY (userid) FOREIGN KEY (RoleID) REFERENCES msm.UsersRole(RoleID)); End;
INSERT INTO [MSM].[UsersMaster] ([userid],[usrname],[loginid],[password],[dept],[RoleID],[ActiveStatus],[IsAdmin],[ColorID],[Background]) VALUES (1, 'admin','admin', 'msm@admin','admin',1,'True','True',11,'BlueViolet');

----------------------------------------------------------------------------------------------------------------------FISCAL YEAR TABLES AND INSERT QUERY-------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.FiscalYear') IS NULL BEGIN CREATE TABLE MSM.FiscalYear(YearID INT NOT NULL,YearDesc VARCHAR(10) NOT NULL, ActiveStatus BIT NULL,PRIMARY KEY (YearID)) END;
INSERT INTO [MSM].[FiscalYear] ([YearID],[YearDesc],[ActiveStatus]) VALUES (1,'77/78',0),(2,'78/79',0),(3,'79/80',1);
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------CONFIGURATION TABLES AND INSERT QUERY-----------------------------------------------------------------------------------------------
IF OBJECT_ID('MSM.Configuration') IS NULL BEGIN CREATE TABLE MSM.Configuration (CID INT NOT NULL,YearID INT NOT NULL,Current_Year VARCHAR(10),IsAdmin BIT,ColorID INT,Background VARCHAR(MAX),VAT DECIMAL(18, 4),Discount DECIMAL(18, 4),checkDate BIT,notes BIT,returnNotes BIT,printMessage BIT, autoPrint BIT, compType INT, billMsg varchar(200), isProduction BIT, PRIMARY KEY (CID),FOREIGN KEY ([YearID]) REFERENCES [MSM].[FiscalYear] ([YearID]))END;
IF OBJECT_ID('[MSM].[Configuration]') IS NOT NULL BEGIN EXECUTE ('INSERT INTO [MSM].[Configuration]([CID],[YearID],[Current_Year],[IsAdmin],[ColorID],[Background],[VAT],[Discount],[checkDate],[notes],[returnNotes],[printMessage],[autoPrint],[compType],[billMsg],[isProduction]) VALUES (1,2,''78/79'',''True'',11,''BlueViolet'',''13'',''0'',''1'',''0'',''1'',''1'',''0'',''0'',''Thank You!'',0)')END;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------COMPANY MASTER INFO TABLE CREATION--------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.CompanyMasterInfo') IS NULL BEGIN CREATE TABLE [MSM].[CompanyMasterInfo] ([Dup_cid] int NOT NULL,[Dup_cname] [varchar](100) NULL,[Dup_regno] [varchar](30) NULL,[Dup_address] [varchar](200) NULL,[Dup_contact] [varchar](50) NULL,[Dup_email] [varchar](100) NULL,[Dup_city] [varchar](100) NULL,[Dup_country] [varchar](20) NULL,[Dup_catalog] [varchar](50) NOT NULL,[Dup_Location] [varchar](100) NULL,[Dup_StateName] [varchar](100) NULL,[Dup_UserID] int,[Dup_DateCreated] datetime,[Dup_MUserID] int,[Dup_ModifiedDate] datetime,PRIMARY KEY (Dup_cid)) END;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------UNIT MASTER INFO TABLE CREATION-----------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.UnitMaster') IS NULL BEGIN CREATE TABLE MSM.UnitMaster( UnitID int NOT NULL,Unit varchar(20),UnitCode varchar(20),[ActiveStatus] [BIT] NULL,UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int null ,ModifiedDate datetime null,FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid) ,FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (userid),primary key (UnitID)) END;
INSERT INTO [MSM].[UnitMaster] ([UnitID],[Unit],[UnitCode],[ActiveStatus],[UserID],[DateCreated],[MUserID],[ModifiedDate]) VALUES (0,'N/A','N/A',1,1,GETDATE(),NULL,NULL),(1,'Pices','PCS',1,1,GETDATE(),NULL,NULL),(2,'Boxes','BOX',1,1,GETDATE(),NULL,NULL),(3,'Dozzen','DZN',1,1,GETDATE(),NULL,NULL),(4,'Packet','PKT',1,1,GETDATE(),NULL,NULL),(5,'Liter','LTR',1,1,GETDATE(),NULL,NULL);
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------STORE GODOWN TABLE CREATION--------------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.StoreGodown') IS NULL BEGIN CREATE TABLE [MSM].[StoreGodown]( [GodID] INT NOT NULL,[GodName] NVARCHAR(80) NULL,[GodCode] NVARCHAR(50) NULL,[GodAddress]  NVARCHAR(50) NULL,[ActiveStatus] BIT NULL,[UserID] INT NULL,[DateCreated] DATETIME NULL,[MUserID] INT	NULL,[ModifiedDate] DATETIME NULL PRIMARY KEY (GodID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid) ,FOREIGN KEY (MUserID) REFERENCES [MSM].[UsersMaster] (userid)) END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------PRODUCT CATEGORY TABLE CREATION----------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.ProductCategory') IS NULL BEGIN CREATE TABLE [MSM].[ProductCategory] ( [CatID] [INT] NOT NULL,[Category] NVARCHAR (100) NOT NULL,[CategoryID] NVARCHAR(10) NOT NULL,[ActiveStatus] [BIT] NULL,[UserID] [INT] NULL,[DateCreated] [DATETIME] NULL,[MUserID] [int] NULL,[ModifiedDate] [datetime] NULL,PRIMARY KEY (CatID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid) ,FOREIGN KEY (MUserID) REFERENCES [MSM].[UsersMaster] (userid)) END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------PRODUCT MASTER TABLE CREATION------------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.ProductMaster') IS NULL BEGIN CREATE TABLE [MSM].[ProductMaster] ( [PID] [int] NOT NUll,PName varchar(MAX),PCode nvarchar(10),PBarcode nvarchar (30),UnitID int null,UnitQnty Decimal(18,6) null,AltUnitId int null,AltUnitQnty Decimal(18,6) null,PurchasePrice money,MRP money,Offer nvarchar(10),PNote varchar(MAX),ProductCategory NVARCHAR(100),ActiveStatus bit NULL,UserID int,DateCreated datetime,MUserID int null,ModifiedDate datetime null,PRIMARY KEY (PID),UNIQUE (PCode),FOREIGN KEY (UnitID) REFERENCES [MSM].[UnitMaster] (UnitID),FOREIGN KEY (AltUnitID) REFERENCES [MSM].[UnitMaster] (UnitID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid) ,FOREIGN KEY (MUserID) REFERENCES [MSM].[UsersMaster] (userid)) END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------CUSTOMER MASTER TABLE CREATION-----------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.CustomerMaster') IS NULL BEGIN CREATE TABLE MSM.CustomerMaster(CID int NOT NULL,PartyName varchar(MAX) NOT NULL,PartyCode nvarchar(10) NOT NULL,PartyEmail varchar(100),PartyCompany varchar(100),PartyAddress nvarchar(MAX),PartyState varchar(100),PartyCountry varchar(20),PartyContact varchar(35),PartyReg nvarchar(50),PartyNote nvarchar(MAX),ActiveStatus bit NULL,UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int null ,ModifiedDate datetime null,PRIMARY KEY (CID),UNIQUE (PartyCode),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid) ,FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (userid)) END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------PURCHASE ORDER---------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.PurchaseOrderMaster') IS NULL BEGIN CREATE TABLE MSM.PurchaseOrderMaster([POID] [int] NOT NULL,[POVNUM] [varchar](20) NOT NULL,[Order_Date] [date] NULL,[Order_Miti] [varchar](10) NULL,[ReceiverID] [int] NULL,[SenderID] [int] NULL,[TransectionOn] [varchar](10),[Total][money],[Vat][decimal](18,4),[VatAmt][money],[TotalAmount][money],[Discount][decimal](18,4),[DiscAmount][money],[BillTotal][money],[InWords][Varchar](MAX),[PO_Bill_Status] [bit] NULL,[UserID] [int] NOT NULL,[DateCreated] [datetime] NOT NULL,[MUserID] [int] NULL,[ModifiedDate] [datetime] NULL,goods_quantity decimal(18,4) NULL,is_Deleted bit,PRIMARY KEY (POID),UNIQUE (POVNUM),FOREIGN KEY (ReceiverID) REFERENCES MSM.CompanyMasterInfo (Dup_cid) ,FOREIGN KEY (SenderID) REFERENCES MSM.CustomerMaster (CID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (userid)) END;
IF OBJECT_ID ('MSM.PurchaseOrderDetails') IS NULL BEGIN CREATE TABLE MSM.PurchaseOrderDetails(POID int NOT NULL,POVNUM varchar(20) NOT NULL,PID INT NOT NULL,PName VARCHAR(MAX) NOT NULL,PCode nvarchar(10),PBarcode nvarchar(30),Quantiy Decimal(18,6) null,UnitID int null,PPrice money,TotalPrice money,PNote varchar(MAX),UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int null,ModifiedDate datetime null,PO_Bill_Status bit null,is_Deleted bit,FOREIGN KEY (POID) REFERENCES MSM.PurchaseOrderMaster (POID),FOREIGN KEY (POVNUM) REFERENCES MSM.PurchaseOrderMaster (POVNUM),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (userid),FOREIGN KEY (UnitID) REFERENCES [MSM].[UnitMaster] (UnitID))END;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


----------------------------------------------------------------------------------VIEWS-------------------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('[MSM].[PurchaseOrder]') IS NOT NULL BEGIN EXECUTE('DROP VIEW [MSM].[PurchaseOrder]') END;
IF OBJECT_ID('[MSM].[PurchaseOrder]') IS NULL BEGIN EXECUTE('CREATE VIEW [MSM].[PurchaseOrder] AS SELECT pom.POID ,pom.POVNUM,pom.Order_Date Purchase_Order_Date,pom.Order_Miti Purchase_Order_Miti,pom.ReceiverID Purchase_Order_Reciver_ID,musrr.usrname Purchase_Order_Creator_Name,cmi.Dup_cname Purchase_Order_Reciver_Company,cmi.Dup_address Purchase_Order_Reciver_Address,cmi.Dup_contact Purchase_Order_Reciver_Contact,pom.SenderID Purchase_Order_Sender_ID,scm.PartyName Purchase_Order_Sender_Name,scm.PartyCompany Purchase_Order_Sender_Company,scm.PartyAddress Purchase_Order_Sender_Address,scm.PartyContact Purchase_Order_Sender_Contact,pom.TransectionOn Transection_Type,pom.Total Total_Before_VAT,pom.Vat Total_VAT,pom.VatAmt Vat_Amount,pom.TotalAmount Amount_After_VAT,pom.Discount Discount_Applied,pom.DiscAmount Discount_Amount,pom.BillTotal Total_Payable_Amount,pom.InWords In_Words,pom.PO_Bill_Status Purchase_Order_Sender_Status,pom.UserID Purchase_Order_Creater_ID,musrr.usrname Purchase_Order_Creator,pom.DateCreated Purchase_Order_Created_Date,pom.MUserID Purchase_Order_Modifier_ID,mmusr.usrname Purchase_Order_Modifier,pom.ModifiedDate Purchase_Order_Modifier_Date,pod.POID Purchase_Order_ID_Details,pod.POVNUM Purchase_Order_Voucher_Number_Details,pod.PID Details_product_ID,pod.PName Details_product,pod.PCode Details_product_Code,pod.PBarcode Details_product_BarCode,pod.Quantiy Details_product_Quantity,pod.UnitID Details_product_UnitID,um.Unit Details_product_Unit,um.UnitCode Details_product_Unit_Code,pod.PPrice Details_product_Purchase_Price,pod.TotalPrice Total_Price,pod.PNote Details_product_Note,pod.UserID ,usr.usrname Details_User,pod.DateCreated ,pod.MUserID,musr.usrname Details_Modified_User,pod.ModifiedDate FROM MSM.PurchaseOrderMaster as pom left outer join MSM.PurchaseOrderDetails as pod on pod.POID = pom.POID left outer join MSM.CompanyMasterInfo cmi on cmi.Dup_cid = pom.ReceiverID left outer join MSM.CustomerMaster scm on scm.CID = pom.SenderID left outer join MSM.UsersMaster musrr on musrr.userid = pom.UserID left outer join MSM.UsersMaster mmusr on mmusr.userid = pom.MUserID left outer join MSM.ProductMaster pm on pm.PID = pod.PID left outer join MSM.UnitMaster um on um.UnitID = pod.UnitID left outer join MSM.UsersMaster usr on usr.userid = pod.UserID left outer join MSM.UsersMaster musr on musr.userid = pod.MUserID WHERE pom.[POID] = pod.POID and pom.[POVNUM] =pod.POVNUM')END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


----------------------------------------------------------------------------------PURCHASE---------------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.PurchaseMaster') IS NULL BEGIN CREATE TABLE MSM.PurchaseMaster(PEID int NOT NULL,PVNUM varchar(20) NOT NULL,Purchase_Date date NULL,Purchase_Miti varchar(10) NULL,ref_bill_No varchar(20) Not Null,Purchase_OrderNo varchar(20) NULL,PO_ReferenceNo varchar(20) NOT NULL,SenderID int NULL,ReceiverID int NULL,TransectionOn varchar(10),Total money,Vat decimal(18,4),VatAmt money,TotalAmount money,Discount decimal(18,4),DiscAmount money,BillTotal money,InWords Varchar(MAX),Note varchar(MAX),PO_Bill_Status bit NULL,is_Deleted bit NULL,UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int NULL,ModifiedDate datetime NULL,extraNote varchar(255),PRIMARY KEY (PEID),UNIQUE (PVNUM),FOREIGN KEY (ReceiverID) REFERENCES MSM.CompanyMasterInfo (Dup_cid),FOREIGN KEY (SenderID) REFERENCES MSM.CustomerMaster (CID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (userid))END;
IF OBJECT_ID ('MSM.PurchaseDetails') IS NULL BEGIN CREATE TABLE MSM.PurchaseDetails(PEID int NOT NULL,PVNUM varchar(20) NOT NULL,PID INT NOT NULL,PName VARCHAR(MAX) NOT NULL,PCode nvarchar(10),PBarcode nvarchar(30),Quantiy Decimal(18,6) null,UnitID int null,PPrice money,TotalPrice money,UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int null,ModifiedDate datetime null,is_Deleted bit NULL,Purchase_OrderNo varchar(20),FOREIGN KEY (PEID) REFERENCES MSM.PurchaseMaster (PEID),FOREIGN KEY (PVNUM) REFERENCES MSM.PurchaseMaster (PVNUM),FOREIGN KEY (PID) REFERENCES MSM.ProductMaster (PID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (userid),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (userid),FOREIGN KEY (UnitID) REFERENCES MSM.UnitMaster (UnitID))END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------PURCHASE RETURN--------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID ('MSM.PurchaseReturnMaster') IS NULL BEGIN CREATE TABLE MSM.PurchaseReturnMaster (PRID INT NOT NULL,PRVNUM VARCHAR(20) NOT NULL,Purchase_Return_Date DATE NULL,Purchase_Return_Miti VARCHAR(10) NULL,SenderID INT NULL,ReceiverID INT NULL,TransectionOn VARCHAR(10),Total MONEY,Vat DECIMAL(18, 4),VatAmt MONEY,TotalAmount MONEY,Discount DECIMAL(18, 4),DiscAmount MONEY,BillTotal MONEY,InWords VARCHAR(MAX),Note VARCHAR(MAX),is_Deleted BIT NULL,UserID INT NOT NULL,DateCreated DATETIME NOT NULL,MUserID INT NULL,ModifiedDate DATETIME NULL,extraNote VARCHAR(255),PRIMARY KEY (PRID),UNIQUE (PRVNUM),FOREIGN KEY (SenderID) REFERENCES MSM.CompanyMasterInfo (Dup_cid),FOREIGN KEY (ReceiverID) REFERENCES MSM.CustomerMaster (CID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID))END;
IF OBJECT_ID('MSM.PurchaseReturnDetails') IS NULL BEGIN CREATE TABLE MSM.PurchaseReturnDetails (PRID INT NOT NULL,PRVNUM VARCHAR(20) NOT NULL,PID INT NOT NULL,PName VARCHAR(MAX) NOT NULL,PCode NVARCHAR(10),PBarcode NVARCHAR(30),Quantiy DECIMAL(18, 6) NULL,UnitID INT NULL,PPrice MONEY,TotalPrice MONEY,Note VARCHAR(MAX) NULL,UserID INT NOT NULL,DateCreated DATETIME NOT NULL,MUserID INT NULL,ModifiedDate DATETIME NULL,is_Deleted BIT NULL,FOREIGN KEY (PRID) REFERENCES MSM.PurchaseReturnMaster (PRID),FOREIGN KEY (PRVNUM) REFERENCES MSM.PurchaseReturnMaster (PRVNUM),FOREIGN KEY (PID) REFERENCES MSM.ProductMaster (PID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (UnitID) REFERENCES MSM.UnitMaster (UnitID))END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------SALES (P.O.S)----------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('MSM.SalesMaster') IS NULL BEGIN CREATE TABLE MSM.SalesMaster (SAID INT NOT NULL,SVNUM VARCHAR(20) NOT NULL,Sales_Date DATE NULL,Sales_Miti VARCHAR(10) NULL,SalerID INT NULL,BuyerID INT NULL,TransectionOn VARCHAR(10),Total MONEY,Vat DECIMAL(18, 4),VatAmt MONEY,TotalAmount MONEY,Discount DECIMAL(18, 4),DiscAmount MONEY,BillTotal MONEY,receivedAmt MONEY NOT NULL,changeGiven MONEY NOT NULL,dueBalance MONEY NOT NULL,InWords VARCHAR(MAX),is_hold BIT NULL,is_Paid BIT NOT NULL,is_complete_paid BIT NOT NULL,Note VARCHAR(MAX),is_Deleted BIT NULL,UserID INT NOT NULL,DateCreated DATETIME NOT NULL,MUserID INT NULL,ModifiedDate DATETIME NULL,extraNote VARCHAR(255),PRIMARY KEY (SAID),UNIQUE (SVNUM),FOREIGN KEY (SalerID) REFERENCES MSM.CompanyMasterInfo (Dup_cid),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID))END;
IF OBJECT_ID('MSM.SalesDetails') IS NULL BEGIN CREATE TABLE MSM.SalesDetails (SAID INT NOT NULL,SVNUM VARCHAR(20) NOT NULL,PID INT NOT NULL,PName VARCHAR(MAX) NOT NULL,PCode NVARCHAR(10),PBarcode NVARCHAR(30),Quantiy DECIMAL(18, 6) NULL,UnitID INT NULL,PPrice MONEY NULL,pDisc MONEY NULL,pamount MONEY	NULL,TotalPrice MONEY,Note VARCHAR(MAX) NULL,UserID INT NOT NULL,DateCreated DATETIME NOT NULL,MUserID INT NULL,ModifiedDate DATETIME NULL,is_Deleted BIT NULL,FOREIGN KEY (SAID) REFERENCES MSM.SalesMaster (SAID),FOREIGN KEY (SVNUM) REFERENCES MSM.SalesMaster (SVNUM),FOREIGN KEY (PID) REFERENCES MSM.ProductMaster (PID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (UnitID) REFERENCES MSM.UnitMaster (UnitID))END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------SALES RETURN----------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('MSM.SalesReturnMaster') IS NULL BEGIN CREATE TABLE MSM.SalesReturnMaster (SRID int NOT NULL,SRVNUM varchar(20) NOT NULL,Sales_Date date NULL,Sales_Miti varchar(10) NULL,Return_Date date NOT NULL,SalerID int NULL,BuyerID int NULL,TransectionOn varchar(10) NULL,Total money NULL,Vat decimal(18, 4) NULL,VatAmt money NULL,TotalAmount money NULL,Discount decimal(18, 4) NULL,DiscAmount money NULL,BillTotal money NULL,InWords varchar(max) NULL,Note varchar(max) NULL,is_Deleted bit NULL,UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int NULL,ModifiedDate datetime NULL,extraNote varchar(255) NULL,status bit NULL,paid_amount money NULL,return_amount money NULL,SAID INT NULL,SVNUM VARCHAR(50) NULL,previous_balance MONEY NULL,sales_bill_amt MONEY null,advance_given MONEY null,PRIMARY KEY (SRID),UNIQUE (SRVNUM),FOREIGN KEY (SalerID) REFERENCES MSM.CompanyMasterInfo (Dup_cid),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID))END;
IF OBJECT_ID('MSM.SalesReturnDetails') IS NULL BEGIN CREATE TABLE MSM.SalesReturnDetails (SRID INT NOT NULL,SRVNUM VARCHAR(20) NOT NULL,PID INT NOT NULL,PName VARCHAR(MAX) NOT NULL,PCode NVARCHAR(10),PBarcode NVARCHAR(30),Quantiy DECIMAL(18, 6) NULL,UnitID INT NULL,PPrice MONEY NULL,pDisc MONEY NULL,pamount MONEY	NULL,TotalPrice MONEY,Note VARCHAR(MAX) NULL,UserID INT NOT NULL,DateCreated DATETIME NOT NULL,MUserID INT NULL,ModifiedDate DATETIME NULL,is_Deleted BIT NULL,FOREIGN KEY (SRID) REFERENCES MSM.SalesReturnMaster (SRID),FOREIGN KEY (SRVNUM) REFERENCES MSM.SalesReturnMaster (SRVNUM),FOREIGN KEY (PID) REFERENCES MSM.ProductMaster (PID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (UnitID) REFERENCES MSM.UnitMaster (UnitID))END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------ORDER TICKET----------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('MSM.OrderMaster') IS NULL BEGIN CREATE TABLE MSM.OrderMaster(OID INT NOT NULL,OVNUM VARCHAR(20) NOT NULL,Order_Date DATE NULL,Order_Miti VARCHAR(10) NULL,Delivery_Date DATE NULL,Delivery_Miti VARCHAR(10) NULL,SenderID INT NULL,BuyerID INT NULL,Est_Time VARCHAR(50) NULL,Note VARCHAR(MAX) NULL,OrderStatus VARCHAR(50) NOT NULL,is_Deleted BIT NULL,UserID INT NOT NULL,DateCreated DATETIME NOT NULL,MUserID INT NULL,ModifiedDate DATETIME NULL,PRIMARY KEY (OID),UNIQUE (OVNUM),FOREIGN KEY (SenderID) REFERENCES MSM.CompanyMasterInfo (Dup_cid),FOREIGN KEY (BuyerID) REFERENCES MSM.CustomerMaster (CID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID))END;
IF OBJECT_ID('MSM.OrderDetails') IS NULL BEGIN CREATE TABLE MSM.OrderDetails(OID int NOT NULL,OVNUM varchar(20) NOT NULL,PID int NOT NULL,PName varchar(max) NOT NULL,PCode nvarchar(10) NULL,PBarcode nvarchar(30) NULL,Quantiy decimal(18, 6) NULL,UnitID int NULL,EST_HrsPerUnit VARCHAR(50) NOT NULL,TotalEST_HrsPerUnit VARCHAR(50) NOT NULL,UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int NULL,ModifiedDate datetime NULL,is_Deleted bit NULL,FOREIGN KEY (PID) REFERENCES MSM.ProductMaster (PID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (UnitID) REFERENCES MSM.UnitMaster (UnitID))END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------ORDER CARD----------------------------------------------------------------------------------------------------------------------------------------------------------
IF OBJECT_ID('MSM.IssueCardMaster') IS NULL BEGIN CREATE TABLE MSM.IssueCardMaster(ICID INT NOT NULL,ICVNUM VARCHAR(20) NOT NULL,OID INT NOT NULL,OVNUM  VARCHAR(20) NOT NULL,Issue_Date DATE NULL,Issue_Miti VARCHAR(10) NULL,Delivery_Date DATE NULL,Delivery_Miti VARCHAR(10) NULL,SenderID INT NULL,BuyerID INT NULL,AssigneeId INT NULL,Est_Time VARCHAR(50) NULL,OrderStatus VARCHAR(50) NULL,Note VARCHAR(MAX) NULL,is_Deleted BIT NULL,UserID INT NOT NULL,DateCreated DATETIME NOT NULL,MUserID INT NULL,ModifiedDate DATETIME NULL,PRIMARY KEY (ICID),UNIQUE (ICVNUM),FOREIGN KEY (SenderID) REFERENCES MSM.CompanyMasterInfo (Dup_cid),FOREIGN KEY (BuyerID) REFERENCES MSM.CustomerMaster (CID),FOREIGN KEY (AssigneeId) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID))END;
IF OBJECT_ID('MSM.IssueCardDetails') IS NULL BEGIN CREATE TABLE MSM.IssueCardDetails(ICID INT NOT NULL,ICVNUM VARCHAR(20) NOT NULL,PID int NOT NULL,PName varchar(max) NOT NULL,PCode nvarchar(10) NULL,PBarcode nvarchar(30) NULL,Quantiy decimal(18, 6) NULL,UnitID int NULL,UserID int NOT NULL,DateCreated datetime NOT NULL,MUserID int NULL,ModifiedDate datetime NULL,is_Deleted bit NULL,FOREIGN KEY (PID) REFERENCES MSM.ProductMaster (PID),FOREIGN KEY (UserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (MUserID) REFERENCES MSM.UsersMaster (UserID),FOREIGN KEY (UnitID) REFERENCES MSM.UnitMaster (UnitID))END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------INVENTORY--------------------------------------------------------------------------------------------------------------------------------------------------------------
--Godown work left
IF OBJECT_ID ('MSM.ProductInventory') IS NULL BEGIN CREATE TABLE MSM.ProductInventory(InventID int,prodID int,Quantity Decimal(18,6),AlternateQuantity decimal(18,6),UnitID int,AltUnitID int null,ActiveStatus bit null,FOREIGN KEY (prodID) REFERENCES MSM.ProductMaster (PID),FOREIGN KEY (UnitID) REFERENCES MSM.UnitMaster (UnitID)) END;
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF OBJECT_ID('MSM.licsence') IS NULL BEGIN CREATE TABLE MSM.licsence(id INT IDENTITY(1,1),licsence_key NVARCHAR(MAX),licsence_Days NVARCHAR(10),issue_date DATETIME,validity_date DATETIME) END;

----------------------------------------------------------------------------------IMP Reference Query---------------------------------------------------------------------------------------------------------------------------------------------------
--IF OBJECT_ID ( 'AMS.SoftwareRegistration' ) IS NULL BEGIN
--EXECUTE ('Alter Table AMS.SoftwareRegistration add Module nvarchar (50), System_Id nvarchar (500), ActivationCode nvarchar (500), Server_MacAdd  nvarchar (500), Server_Desc nvarchar (50);')
--END;